import { Button } from './ui/button';
import { Card, CardContent, CardHeader, CardTitle } from './ui/card';
import { Separator } from './ui/separator';
import { ArrowLeft, Printer, Download, Activity } from 'lucide-react';
import type { Patient, Prediction } from '../utils/types';

interface ReportViewProps {
  patient: Patient;
  prediction: Prediction;
  onBack: () => void;
}

export function ReportView({ patient, prediction, onBack }: ReportViewProps) {
  const handlePrint = () => {
    window.print();
  };

  const handleDownload = () => {
    const reportContent = generateReportText();
    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `DR_Report_${patient.lastName}_${patient.firstName}_${new Date(prediction.createdAt).toISOString().split('T')[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const generateReportText = () => {
    return `
DIABETIC RETINOPATHY SCREENING REPORT
======================================

Report Generated: ${new Date().toLocaleString()}

PATIENT INFORMATION
-------------------
Name: ${patient.firstName} ${patient.lastName}
Medical Record Number: ${patient.medicalRecordNumber || 'N/A'}
Date of Birth: ${new Date(patient.dateOfBirth).toLocaleDateString()}
Gender: ${patient.gender}
${patient.diabetesType ? `Diabetes Type: Type ${patient.diabetesType}` : ''}
${patient.diagnosisDate ? `Diabetes Diagnosis Date: ${new Date(patient.diagnosisDate).toLocaleDateString()}` : ''}

SCREENING DETAILS
-----------------
Screening Date: ${new Date(prediction.createdAt).toLocaleString()}
Analysis Method: AI-Powered Ensemble Model

RESULTS
-------
Detected Stage: ${prediction.stage}
Confidence Score: ${(prediction.confidence * 100).toFixed(1)}%

CLINICAL RECOMMENDATION
-----------------------
${prediction.recommendation}

IMPORTANT NOTES
---------------
- This screening result is generated by an AI-assisted diagnostic tool
- Results should be reviewed by a qualified healthcare professional
- This report is intended to support clinical decision-making, not replace it
- Follow-up care should be based on clinical judgment and patient circumstances

For questions or concerns, please consult with an ophthalmologist or retinal specialist.
    `.trim();
  };

  const getSeverityColor = (stage: string) => {
    switch (stage) {
      case 'No DR':
        return 'bg-green-100 text-green-800';
      case 'Mild DR':
        return 'bg-yellow-100 text-yellow-800';
      case 'Moderate DR':
        return 'bg-orange-100 text-orange-800';
      case 'Severe DR':
        return 'bg-red-100 text-red-800';
      case 'Proliferative DR':
        return 'bg-purple-100 text-purple-800';
      default:
        return 'bg-gray-100 text-gray-800';
    }
  };

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="no-print mb-6 flex items-center justify-between">
          <Button variant="ghost" onClick={onBack}>
            <ArrowLeft className="w-4 h-4 mr-2" />
            Back to Dashboard
          </Button>
          <div className="flex gap-3">
            <Button variant="outline" onClick={handleDownload}>
              <Download className="w-4 h-4 mr-2" />
              Download
            </Button>
            <Button onClick={handlePrint}>
              <Printer className="w-4 h-4 mr-2" />
              Print Report
            </Button>
          </div>
        </div>

        <Card className="print:shadow-none">
          <CardHeader className="space-y-4">
            <div className="flex items-center gap-3">
              <Activity className="w-8 h-8 text-blue-600" />
              <div>
                <CardTitle className="text-2xl">Diabetic Retinopathy Screening Report</CardTitle>
                <p className="text-sm text-gray-500 mt-1">AI-Powered Diagnostic Analysis</p>
              </div>
            </div>
            <div className="text-right text-sm text-gray-500">
              Report Generated: {new Date().toLocaleString()}
            </div>
          </CardHeader>

          <CardContent className="space-y-6">
            {/* Patient Information */}
            <div>
              <h3 className="text-gray-900 mb-3">Patient Information</h3>
              <div className="grid grid-cols-2 gap-x-8 gap-y-2 text-sm">
                <div>
                  <span className="text-gray-600">Name:</span>{' '}
                  <span className="text-gray-900">{patient.firstName} {patient.lastName}</span>
                </div>
                <div>
                  <span className="text-gray-600">Medical Record Number:</span>{' '}
                  <span className="text-gray-900">{patient.medicalRecordNumber || 'N/A'}</span>
                </div>
                <div>
                  <span className="text-gray-600">Date of Birth:</span>{' '}
                  <span className="text-gray-900">{new Date(patient.dateOfBirth).toLocaleDateString()}</span>
                </div>
                <div>
                  <span className="text-gray-600">Gender:</span>{' '}
                  <span className="text-gray-900">{patient.gender}</span>
                </div>
                {patient.diabetesType && (
                  <div>
                    <span className="text-gray-600">Diabetes Type:</span>{' '}
                    <span className="text-gray-900">Type {patient.diabetesType}</span>
                  </div>
                )}
                {patient.diagnosisDate && (
                  <div>
                    <span className="text-gray-600">Diabetes Diagnosis Date:</span>{' '}
                    <span className="text-gray-900">{new Date(patient.diagnosisDate).toLocaleDateString()}</span>
                  </div>
                )}
              </div>
            </div>

            <Separator />

            {/* Screening Details */}
            <div>
              <h3 className="text-gray-900 mb-3">Screening Details</h3>
              <div className="grid grid-cols-2 gap-x-8 gap-y-2 text-sm">
                <div>
                  <span className="text-gray-600">Screening Date:</span>{' '}
                  <span className="text-gray-900">{new Date(prediction.createdAt).toLocaleString()}</span>
                </div>
                <div>
                  <span className="text-gray-600">Analysis Method:</span>{' '}
                  <span className="text-gray-900">AI-Powered Ensemble Model</span>
                </div>
              </div>
            </div>

            <Separator />

            {/* Fundus Image */}
            <div>
              <h3 className="text-gray-900 mb-3">Fundus Photograph</h3>
              <img
                src={prediction.imageUrl}
                alt="Fundus"
                className="w-full max-w-md mx-auto rounded-lg border border-gray-200"
              />
            </div>

            <Separator />

            {/* Results */}
            <div>
              <h3 className="text-gray-900 mb-3">Analysis Results</h3>
              <div className="space-y-4">
                <div>
                  <p className="text-sm text-gray-600 mb-2">Detected Stage</p>
                  <div className={`inline-block px-4 py-2 rounded-lg ${getSeverityColor(prediction.stage)}`}>
                    <span className="text-lg">{prediction.stage}</span>
                  </div>
                </div>
                <div>
                  <p className="text-sm text-gray-600 mb-2">Confidence Score</p>
                  <p className="text-2xl text-gray-900">{(prediction.confidence * 100).toFixed(1)}%</p>
                </div>
              </div>
            </div>

            <Separator />

            {/* Clinical Recommendation */}
            <div>
              <h3 className="text-gray-900 mb-3">Clinical Recommendation</h3>
              <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
                <p className="text-gray-900">{prediction.recommendation}</p>
              </div>
            </div>

            <Separator />

            {/* Important Notes */}
            <div>
              <h3 className="text-gray-900 mb-3">Important Notes</h3>
              <ul className="text-sm text-gray-600 space-y-1 list-disc list-inside">
                <li>This screening result is generated by an AI-assisted diagnostic tool</li>
                <li>Results should be reviewed by a qualified healthcare professional</li>
                <li>This report is intended to support clinical decision-making, not replace it</li>
                <li>Follow-up care should be based on clinical judgment and patient circumstances</li>
              </ul>
              <p className="text-sm text-gray-600 mt-4">
                For questions or concerns, please consult with an ophthalmologist or retinal specialist.
              </p>
            </div>
          </CardContent>
        </Card>
      </div>

      <style>{`
        @media print {
          .no-print {
            display: none !important;
          }
          body {
            background: white;
          }
        }
      `}</style>
    </div>
  );
}
